AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              # TODO implement
              return {
                  'statusCode': 200,
                  'body': json.dumps('Hello from Lambda!!!!!!!!!')
              }
      FunctionName:
        Ref: LambdaFuncName
      Handler: index.handler
      Runtime: python3.6
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::549289340310:role/Lambdaroleforcfcf
Parameters:
  LambdaFuncName:
    Type: String
    Default: Lambda_api-lambda-db
