AWSTemplateFormatVersion: 2010-09-09
Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: "testtestbucket2021"
        S3Key:
          Fn::Sub: "LambdaCode/lambda_function.py"
      FunctionName:
        Ref: LambdaFuncName
      Handler: index.handler
      Runtime: python3.6
      Timeout: 900
      Role:
        Fn::Sub: arn:aws:iam::549289340310:role/MyLambdaRole
Parameters:
  LambdaFuncName:
    Type: String
    Default: Lambda_api-lambda-db
